---
title: "index"
author: "Adam"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
source("Analysis.R")
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
You have requested information about the album: `r album_name`. This album has `r length(track_names)` songs. 

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
# Simple Horizontal Bar Plot with Added Labels
par(mai=c(1,1.5,1,1))
par(bg = 'grey')
barplot(track_length, main="Songs vs Length",xlab = "Length", horiz=TRUE,
  names.arg=rev(track_names), col = 'red', las = 1)

```

```{r newPlot}
ggplot(data=album_df, aes(x=track_names, y=track_length)) +
  ggtitle("Songs vs length")+
    annotation_custom(rasterGrob(album_cover, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                               -Inf, Inf, -Inf, Inf)+
  geom_bar(stat="identity", position = "stack", colour = 'black', alpha = 0.5, width = 1) +
   coord_flip() 

   
```
